from pptx import Presentation
from pptx.util import Inches


def create_ppt(title: str, content: str, filename: str = "output.pptx"):
    """
    Generates a PowerPoint presentation with a title slide and content.
    """
    prs = Presentation()

    # Add title slide
    slide_layout = prs.slide_layouts[0]  # Title Slide Layout
    slide = prs.slides.add_slide(slide_layout)
    title_placeholder = slide.shapes.title
    subtitle_placeholder = slide.placeholders[1]
    title_placeholder.text = title
    subtitle_placeholder.text = "Generated by pptcourse"

    # Add content slide
    slide_layout = prs.slide_layouts[5]  # Title + Content Layout
    slide = prs.slides.add_slide(slide_layout)
    title_placeholder = slide.shapes.title
    content_placeholder = slide.placeholders[1]
    title_placeholder.text = "Content"
    content_placeholder.text = content

    # Save the PowerPoint file
    prs.save(filename)
    print(f"PPT saved as {filename}")